### ISSUE TITLE
JsonMappingException: Can not resolve PropertyFilter with id 'validateFilter'; no FilterProvider configured

### ISSUE THREAD

**Issue by velouria** [bitzeche/jpasskit#38]
In PKSigningUtil when calling createManifestJSONFile when using jackson-databind version >= 2.3.0.
Tried with both release 0.0.4 and 0.0.5-20140809 and got:

com.fasterxml.jackson.databind.JsonMappingException: Can not resolve PropertyFilter with id 'validateFilter'; no FilterProvider configured
     at com.fasterxml.jackson.databind.ser.std.StdSerializer.findPropertyFilter(StdSerializer.java:274)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:401)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
     at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
     at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2866)
     at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2272)
     at de.brendamour.jpasskit.signing.PKSigningUtil.createManifestJSONFile(PKSigningUtil.java:381)
     at de.brendamour.jpasskit.signing.PKSigningUtil.createSignedAndZippedPkPassArchive(PKSigningUtil.java:110)

**Comment by Haiperlink** [comment]
Hi @drallgood 
are there any plans for an update to a newer version? 
Jackson 2.2.3 is from 2013. Are there any known issues to update this to a current version?

**Comment by drallgood** [comment]
@Haiperlink Oh. Thanks for the reminder. Completely forgot about it.
Gonna work on it right away

**Comment by Haiperlink** [comment]
@drallgood that's great news. Thank you for the effort.

**Comment by drallgood** [comment]
I've just releases jPasskit 0.0.5 with updated dependencies.
Please let me know whether there are any issues left

**Comment by Haiperlink** [comment]
Thank you for your fast reaction, I've upgraded to 0.0.5, but unfortunately I still have the same issue as @velouria 
any idea?

**Comment by Haiperlink** [comment]
jackson 2.5.3

>com.fasterxml.jackson.databind.JsonMappingException: Can not resolve PropertyFilter with id 'validateFilter'; no FilterProvider configured

> …kson.databind.ser.std.StdSerializer.findPropertyFilter (StdSerializer.java:285)
…erxml.jackson.databind.ser.std.MapSerializer.serialize (MapSerializer.java:459)
…erxml.jackson.databind.ser.std.MapSerializer.serialize (MapSerializer.java:29)
….databind.ser.DefaultSerializerProvider.serializeValue (DefaultSerializerProvider.java:129)
…xml.jackson.databind.ObjectMapper._configAndWriteValue (ObjectMapper.java:3385)
 com.fasterxml.jackson.databind.ObjectMapper.writeValue (ObjectMapper.java:2728)
….jpasskit.signing.PKSigningUtil.createManifestJSONFile (PKSigningUtil.java:381)
…gning.PKSigningUtil.createSignedAndZippedPkPassArchive (PKSigningUtil.java:110)

**Comment by drallgood** [comment]
Ok. I think I might have fixed it. 
I have no way of verifying it, though. Could you please give it a try (by using the current SNAPSHOT) instead)?

**Comment by Haiperlink** [comment]
0.0.6-SNAPSHOT seems to work great!
Thank you very much for your help.

Und schöne Grüße nach Koblenz. Ich bin direkt nebenan in Neuwied aufgewachsen. ;-)

**Comment by drallgood** [comment]
Awesome. Just released it :)

Thanks for reporting this!

**Comment by drallgood** [comment]
Und Grüße nach Zürich. Fahre morgen quasi in die Nähe zu meiner Family (nähe Schaffhausen)

**Comment by Haiperlink** [comment]
A small world :)



—

**Comment by velouria** [comment]
Also tried with 0.0.6 and the latest released versions of jackson-core and jackson-databind and it worked fine. :)
Thanks!

**Comment by dailymartin** [comment]
I meet this error, now.
I use 0.0.8 and jackson 2.8.1.
Is there anybody can help me?

**Comment by dailymartin** [comment]
@stepio Of course, thanks :)

**Comment by dailymartin** [comment]
@stepio 
It's my fault. Thanks anyway.

**Comment by stepio** [comment]
Great, you're welcome :)
